### ISSUE TITLE
KubeIngressProxy docs

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#163]
While working on a PR (#161) I came across [`KubeIngressProxy`](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/proxy.py). I'm hoping to learn where and how it is used in order to be able to make a thorough PR that doesn't break things or leave the repo in an inconsistent state.

### TODO
- [ ] Comprehend where `KubeIngressProxy` is used
- [ ] Comprehend how `KubeIngressProxy` is used
- [ ] Create a docstrings for the KubeIngressProxy class definition
- [ ] Consider exporting `KubeIngressProxy` as well from [`__init__.py`](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/__init__.py) along with KubeSpawner.

/cc: @minrk @yuvipanda as you have contributed to `proxy.py`

**Comment by clkao** [comment]
This seems to be an alternative proxy class implemented as k8s operator that manages the ingress' route table directly for the hub and spawned user notebooks, replacing the default `configurable-http-proxy`.  It can be configured with `c.JupyterHub.proxy_class`

There are some explanation and diagram in [the slides](https://indico.cern.ch/event/663264/contributions/2863771/attachments/1591005/2517845/erokhin_spbu_swan_final.pdf).  I am also curious about the status of the implementation and if anyone uses it in production.

If this is working well it should be (optionally) enabled for z2jh as a more native ingress-based proxy.

**Comment by gweis** [comment]
Hi, ... I played around with it, and I can say that it works, but it needed a bit of tweaking for my environment to play nice with nginx ingress controller.

1. I patched the kubespawner.objects.make_ingress method to include ingress.spec.rule.host property (which is only populated if you use per user sub domains), and I have added some TLS setup as well there. After that it was all good.
2. You have to make sure that notebooks and jupyterhub run the same version, otherwise jupyterhub will bail out due to a redirect loop too early. (It takes a little bit for the ingress controller to configure the route)

Otherwise it seems to be working well and hub and notebooks feel a bit faster as well (one less proxy and bottleneck in the request chain).

I guess what's missing is an easier way to configure the proxy to make it more flexible for different deployment scenarios. Also I am not sure how well route clean up and update works after hub restart (having some issues there every now and then). Another thing I was wondering is, whether it could work without managing endpoints directly. e.g. use pod labels and services targeting pods by label and let kubernetes manage the endpoints. (probably depends on cluster configuration and deployment scenario as well)

Additionally, my cull-idle-servers services (external service), needs some updating as well. 
I do expect some other rough edges, especially around external hostname setup, and external services needing to talk to hub and notebooks.

**Comment by clkao** [comment]
related to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/710 and https://github.com/kubeflow/kubeflow/issues/239
