### ISSUE TITLE
Planning release of v7

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#850]
I'm looking to get a release out to unblock the next z2jh major release with JupyterHub 5. I'm not sure what remains, but this issue can track it.

## Todo

- [x] check in on open PRs to consider if they can land quickly
- [x] changelog writing
  - [x] pr categorization
  - [x] breaking changes communication
- [x] kubespawner 7 beta release
- [x] Erik tests things described in https://github.com/jupyterhub/kubespawner/pull/744#issuecomment-2259964710
